name: Backend - Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./backend
          tags: ghcr.io/${{ github.repository }}/backend:${{ github.sha }}

  update-argo-deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: fwastring/argocd-bike-guide
          token: ${{ secrets.GITOPS_TOKEN}}

      - name: Update Kubernetes deployment with new image tag
        run: |
          # Update the deployment.yaml with the new image tag (ghcr.io/${{ github.repository }}/backend:${{ github.sha }})
          sed -i 's|image: ghcr.io/${{ github.repository }}/backend:.*|image: ghcr.io/${{ github.repository }}/backend:${{ github.sha }}|' k8s/deployment.yml

          # Commit and push the changes to the repository
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add k8s/deployment.yml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin main
