name: Backend - Build and Push

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
      backend: ${{ steps.changes.outputs.backend }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for changes
        id: changes
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed files: $files"
          frontend_changes=false
          backend_changes=false
          if [[ "$files" == *"frontend/"* ]]; then
            frontend_changes=true
          fi
          if [[ "$files" == *"backend/"* ]]; then
            backend_changes=true
          fi
          echo "::set-output name=frontend::$frontend_changes"
          echo "::set-output name=backend::$backend_changes"

  backend:
    if: ${{ needs.check-changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./backend
          tags: ghcr.io/${{ github.repository }}/backend:${{ github.sha }}

  backend-deployment:
    runs-on: ubuntu-latest
    if: ${{ needs.check-changes.outputs.backend == 'true' }}
    needs: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: fwastring/argocd-bike-guide
          token: ${{ secrets.GITOPS_TOKEN}}

      - name: Update Kubernetes deployment with new image tag
        run: |
          # Update the deployment.yaml with the new image tag (ghcr.io/${{ github.repository }}/backend:${{ github.sha }})
          sed -i 's|image: ghcr.io/${{ github.repository }}/backend:.*|image: ghcr.io/${{ github.repository }}/backend:${{ github.sha }}|' k8s/deployment.yml

          # Commit and push the changes to the repository
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add k8s/deployment.yml
          git commit -m "Update backend image tag to ${{ github.sha }}"
          git push origin main

  frontend:
    if: ${{ needs.check-changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./backend
          tags: ghcr.io/${{ github.repository }}/backend:${{ github.sha }}


  frontend-deployment:
    runs-on: ubuntu-latest
    if: ${{ needs.check-changes.outputs.frontend == 'true' }}
    needs: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: fwastring/argocd-bike-guide
          token: ${{ secrets.GITOPS_TOKEN}}

      - name: Update Kubernetes deployment with new image tag
        run: |
          # Update the deployment.yaml with the new image tag (ghcr.io/${{ github.repository }}/backend:${{ github.sha }})
          sed -i 's|image: ghcr.io/${{ github.repository }}/frontend:.*|image: ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}|' k8s/deployment.yml

          # Commit and push the changes to the repository
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add k8s/deployment.yml
          git commit -m "Update frontend image tag to ${{ github.sha }}"
          git push origin main
